defaults:
  - _self_
  - policy@_global_: default
  - task@_global_: wikidata_counterfact
  - base_model@_global_: llama32i1b
  - optimization@_global_: reinforce
  - mode@_global_: training

num_iters: 10
test_interval: 10
lr: 2e-3
batch_size: 256
seed: 42
init_val: 0.1
test_only: false
model_dir: null
save_legacy_params: false
use_lora: false
prompt_based_eval: false
experts_path_dict: null

run_name: null

load_ckpt: null
exp_suffix: 'st'

exp_name: ${base_model_name}/${optim_name}-${exp_suffix}

wandb_log: true # enabled by default
wandb_project: burnaeff
wandb_group_name: ${exp_name}
extract_svd: false

out_dir: results

hydra:
  run:
    dir: ${out_dir}/
